### ISSUE TITLE
Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by azizullah-masology** [omansak/libvideo#75] opened 2017-05-24 12:01 UTC
Hi 

I am working on a project that download videos/audios form youtube using libvideo. But I am having issue with some of the videos, they are throwing exception 403. Following is my code:

` var downloadFolder = Environment.GetFolderPath(Environment.SpecialFolder.MyMusic) + "\\" + channelName;

            var youTube = YouTube.Default;
            var audio = youTube.GetAllVideos(string.Format(url))
                                    .Where(vdeo => vdeo.AdaptiveKind == AdaptiveKind.Audio)
                                    .OrderByDescending(vdeo => vdeo.AudioBitrate)
                                    .FirstOrDefault();

            var path = Path.Combine(downloadFolder, audio.Title);
            if (!File.Exists(path))
                File.WriteAllBytes(path, audio.GetBytes());`

I copied the uri for video from audio object and pasted in the browser, it is showing same error: 
Access to r1---sn-4wg7ln7e.googlevideo.com was denied
You don't have authorization to view this page.
HTTP ERROR 403

Could anyone please help me...

**Comment by Tyrrrz** [comment] 2017-05-26 08:31
What's the ID

**Comment by azizullah-masology** [comment] 2017-05-26 09:26
Thanks for replay... @Tyrrrz 
The ID of video?? if u are asking the id of video, it is... for example this video: kv63n_rfJwk
The url for this video is: https://www.youtube.com/watch?v=kv63n_rfJwk
I tried multiple videos to download by above code... some of the videos are downloading and some throw 403 exemption.

**Comment by Tyrrrz** [comment] 2017-05-26 13:24
Hm seems to work in [YoutubeExplode](https://github.com/Tyrrrz/YoutubeExplode), you can use that instead if you want a quick solution

**Comment by KiLLeRRaT** [comment] 2017-10-04 21:56
I'm also getting this issue.

**Comment by Zinshis** [comment] 2017-10-17 22:29
I have come across the same issue, but might have found the cause.

It would appear that the _DecryptFunction_ in _YoutubeVideo.Decrypt.cs_ does not seem to find the javascript "decrypt" function. It is searching for a function along the lines of "foo.sig||bar(baz)", but now the function needs to be (at least in my experience) "d.set("signature",bar(c))"", where "bar" is the function we're looking for.

Changing the code in the _DecryptFunction_ to look for the new function signature solved my issue.
Video url that used to fail, but now works: https://www.youtube.com/watch?v=zYoG7vTLpZk

**Comment by i3arnon** [comment] 2018-04-10 12:48
Hey @azizullah-masology,
I think I fixed your issue and this video works for me with the latest beta version (https://www.nuget.org/packages/VideoLibrary/1.3.6-beta).
I'm closing this issue but please tell me if you have any issues.

**Closed as completed by i3arnon** 2018-04-10 12:48 UTC

**Comment by muwal-jitender** [comment] 2018-10-01 10:19
Hi @i3arnon ,

I was facing an issue **GetDecryptionFunction failed** and for that I followed the link https://github.com/i3arnon/libvideo/pull/103 and it has fixed my issue. I updated to VideoLibrary  **versiom 2.0.1** and didn't get that error again.
But after that I have started getting the exception "Response status code does not indicate success: 403 (Forbidden) "
When I came here and found that this issue had been fixed under **1.3.6-beta**. But now it seems that the issue 403 forbidden again got introduced in version 2.0.1. Can you please help me out in this?

One more important thing that when the code ` var videos = youTube.GetAllVideos(link).ToList();` returns the object containing **IsEncrypted=true** for the given video link, throws the exception, whereas any links contains it as **false**  is working fine.

**Comment by jayotirana** [comment] 2018-10-01 12:37
Hi @muwal-jitender 
version: 2.0.1 (1.3.6-beta will also not work)
For the exception that you are getting i.e, Response status code does not indicate success: 403 (Forbidden)
The reason behind this may be the "You don't have the authorization to view this page.". 

Thanks

**Comment by i3arnon** [comment] 2018-10-13 16:16
@muwal-jitender 
[Version 2.0.2](https://www.nuget.org/packages/VideoLibrary/2.0.2) that I recently published should fix it.
